import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '../components/general/Layout'
import { trpc } from '../utils/trpc'

export default function Home() {

  return (
    <Layout>
      <Head>
        <title>Que prefieres?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>LANDING PAGE</h1>
      </main>
    </Layout>
  )
}
